version: '2.3'
services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

  mongodb:
    image: mongo:3
    container_name: mongo
    command: mongod --smallfiles
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    container_name: elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - graylog-network
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  graylog:
    image: graylog/graylog:3.0.0-1
    container_name: graylog
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    networks:
      - traefik-network
      - graylog-network
    labels:
      - "traefik.enable=true"
      - "traefik.web.port=9000"
      - "traefik.web.frontend.rule=Host:graylog.localhost"
      - "traefik.web.backend.healthcheck.path=/"
      - "traefik.web.backend.healthcheck.interval=10s"
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.localhost/
      - GRAYLOG_ROOT_TIMEZONE=Europe/Helsinki
    depends_on:
      mongodb:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      
networks:
  traefik-network:
    external: true
  graylog-network:
    external: false

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local